### ISSUE TITLE
Andmebaasi skoop ja ülesehitus

### ISSUE THREAD

**Issue by martlaus** [kaarelkivistik/andmebaasid#2]
Teeme veebipoe.

Tabelid on:
  products
  warehouses
  inventory
  users

**Comment by kaarelkivistik** [comment]
veel tabeleid:

baskets (ostukorvid - user ID, date jne)
basket_products (basket ID, product ID, quantity)

orders

**Comment by martlaus** [comment]
Ilmselt on vaja ka seisundit/seisundeid.
  basket_state(basket id, date, esitatud/kinnitatud/tellitud/saadetud

**Comment by kaarelkivistik** [comment]
state ongi juba _baskets_ tabelis ju

**Comment by martlaus** [comment]
Ma netist leidsin mingeid näiteid, kus seisundite jaoks oli eraldi tabel, aga lihtsam on vist ilma lisatabeliteta?

**Comment by kaarelkivistik** [comment]
imho küll ei ole eraldi state tabelit vaja - meie e-poes ei ole vaja säilitada ühe ostukorvi olekute ajalugu, too hardcore
