### ISSUE TITLE
Olemitüübid

### ISSUE THREAD

**Issue by kaarelkivistik** [kaarelkivistik/andmebaasid#3]
1. Product
2. Order
3. Warehouse
4. User
5. Product state _klassifikaator_
6. Order type _klassifikaator_
7. Order state _klassifikaator_

**Comment by martlaus** [comment]
Kas klassifikaatorid on põhiolemitüübid?

**Comment by SiimKaasik** [comment]
Eessaar andis sellise lehekülje: http://schema.org/Product, kust saab andmebaasi kavandamisel toodete kohta ideid. Ehk siis mida potensiaalselt võiks kauba või toote kohta andmebaasi kirja panna.
