### ISSUE TITLE
Siimu märkmed Eessaare jutust

### ISSUE THREAD

**Issue by martlaus** [kaarelkivistik/andmebaasid#5]
SQL koodis:
1) Kood - klassifikaator 
2) bigint asemel kasutada midagi väiksemat (küsimus on semantikas)
3) Seisundi_kood ei ole default valuet. Lisada default value.
4) Tuleks panna juurde riigi klassifikaator
5) Seisund muuta kauba_seisund
6) Nimed on erinevad - eesnimed, perenimed, isanimi. Mitte ühe varchar all

Dokumendis:
1) CRUD maatriksis pole kõiki olemitüüpe
2) Arvustus lisada eraldi põhiobjektiks
3) CRUD maatriksis kauba_omadus 5: CRUD
4) Kauba loomisel anda ette viide tootjale
5) Kasutajanimi teha unikaalseks
6) E-mail teha unikaalseks
7) Võib teha nii, et kasutajanime kaotame ära ja kasutame e-maili kasutajanimena (peab olema unikaalne)
8) Kaubal pole staatust
9) Tarneaeg: tuleb kirja panna, et võib sisaldada komakohti ja ei tohi olla negatiivne
10) Hind: valuuta, kas võib olla negatiivne, kas võib olla null, kas sisaldab makse, 
    kas on sisseostuhind või väljamüügihind, kas võib olla komakohti
11) Kasutusjuhud: tuleb lahti kirjutada
12) Punkt "2.1 Kaupade arvestuse funktsionaalne allsüsteem 2.1.1 Kasutusjuhtude mudel" on puudu
13) Kauba omadusel on atribuut nimega "Väärtus", mis meil puudub

Prototüübis:
1) Kohustuslikud väljad tuleb tärniga tähistada

**Comment by kaarelkivistik** [comment]
minu variant

*kood -> ...._kood ja tüüp ei peaks olema bigint (nii palju andmeid ei tule)
*klassifikaatori koodid registreerib kasutaja (ei peaks olema autoincrement)
*kategooria, omaduse nimetus peab olema unique
*kauba seisundi kood ei tohi olla null (samamoodi ka tarnija, töötaja jnejne)
*organisatsioonile juurde riigi klassifikaator ja juurde
*töötaja nimi -> eesnimi ja perenimi
*töötaja e-mail unikaalseks
*töötaja PK_isikukood asemel PK_töötaja_kood (isikukood ei pruugi olla unikaalne mitme riigi piires)
*arvustuste funktsionaalne allsüsteem (mujalt likvideerida)
*klassifikaatorid tuleb crud-maatriksis kirjutada lahti
*delete operatsioon nahhui
*kauba_omadus -> CRUD (lisad, muudad, kustutad)
*kauba aktiivseks muutmine ja kauba mitteaktiivseks muutmine on kaks eraldi juhendud
*lepingute parameetrid (kauba loomisel oli puudu töötaja nt)
*kauba staatus ??? (andmebaasis "seisund")
*paljud väärtused ei tohiks olla negatiivsed
*2.1.1 kasutusjuhtude mudel
*ea projektis üldistustele lisada kitsendused (mauruses video olemas)
*association class kontseptuaalses andmemudelis (mitu-mitu suhe ja panna juurde association klass Kauba_omadus)
*prototüübis peavad kohustuslikud väljad olema tärniga

Kaup
*kas hind võib olla negatiivne, null (hint - ei või); valuuta; väljamüügi hind
*KaubaOmadusel kaup_kood ja omadus_kood peavad olema unique
*paljud asjad ei tohi olla not null

**Comment by martlaus** [comment]
Hetkel tehtud: 
lihtsalt väljamüügi hind - tehtud
arvustus on põhiobjekt ja saab eraldi registrid ja jutud -tehtud
2) Arvustus lisada eraldi põhiobjektiks -tehtud
staatus aktiivne ja mitteaktiivne kõik eraldi juhud igalpool - tehtud
1) CRUD maatriksis pole kõiki olemitüüpe -  igalpool pandud klassifikaatorite olemitüübid paika koos kirjeldustega
3) CRUD maatriksis kauba_omadus 5: CRUD - tehtud ja igalpool kooskõlas
5) Seisund muuta kauba_staatus - igalpool on nüüd STAATUS, mitte seisund, kõik kooskõlas
4) Kauba loomisel anda ette viide tootjale -  siin vist oli mõeldud Töötajat, tegin ära
Hakkasin muutma ärireegleid, a'la hinne on positiivne ja 0-5, email on kasutajatunnus ja unikaalne jne jne, neid peate kõik ise juurde mõtlema ja siis vastavalt parandama Atribuutide definitsioondies.
5) Kasutajanimi teha unikaalseks - seda pole enam, aint email
6) E-mail teha unikaalseks -olemas
7) Võib teha nii, et kasutajanime kaotame ära ja kasutame e-maili kasutajanimena (peab olema unikaalne) - seda tegingi
8) Kaubal pole staatust - nüüd on

**Comment by SiimKaasik** [comment]
Tehtud lisaks:
9) Tarneaeg: panin kirja, et võib sisaldada komakohti ja ei tohi olla null.
10) Hind: Panin kirja, et valuuta on euro, ei tohi olla negatiivne ega null, sisaldab käibemaksu ja võib sisaldada komakohti.
12) 2.1.1 Kasutusjuhtude mudel ( ei osanud täpselt igale poole laiendusi lisada - neid peaks veel lisama )
