### ISSUE TITLE
Teise kaitsmise tagasiside

### ISSUE THREAD

**Issue by martlaus** [kaarelkivistik/andmebaasid#6]
default null atribuutide definitsiooni
klassifikaatoreid ei uuenda, neid ainult loeme CRUDis
unikaalne nimetus
Tabelis riik kolm eraldi UNIQUE keyd nimi klassifikaator2 ja klassifikaator3
nimetus unikaalne kategoorias ja staatuses
riigis pole id-d vaja, seal on juba 2tähte ja 3tähte unikaalne
välisvõtmeid ei nimetata
Klassifikaatorite tabelit pole kuhugi vaja
atribuutides väärtus NULL asenda sellega et on kohustuslik
Kauba aktiivseks seadmisel kasutame operatsiooni, mis näitab kauba infot
riik ja registri kood peab olema unique kombinatsioon
klassifikaatorit pole kuhugi vaja

**Comment by SiimKaasik** [comment]
Andmebaaside parandusel Vol 2

1) UNIQUE KEY `UK_riik_on_unikaalne` (`nimi`,`identifikaator2tahte`,`identifikaator3tahte`)

Kolm korda eraldi vaja deklareerida, sest muidu on kolme kombinatsioon unikaalne mitte igaüks ise

2)  `riigi_kood` smallint(6) NOT NULL,
  `identifikaator2tahte` varchar(2) NOT NULL,
  `identifikaator3tahte` varchar(3) NOT NULL,

  miks ei ole primary key

3)  kauba_kategooria nimetus unikaalne
    kuskil veel nimetus unikaalne

4) kaup.kauba_staatus =
aga kaubal pole sellist atribuuti nagu kauba_staatus

5) klassifikaatori võib ära kustutada

6) registri_koodi ja riigi kombinatsioon peab olema unique

**Comment by kaarelkivistik** [comment]
palju paremad märkmed kui mardi omad (H)
