### ISSUE TITLE
Harjutustunni tagasiside

### ISSUE THREAD

**Issue by kaarelkivistik** [kaarelkivistik/andmebaasid#7]
1. hinna andmetüüp millekski mõistlikumaks -> decimal(10, 2)
2. riigi kood varchar(2) -> char(2)
3. töötaja saab olla ainult eestist (isikukood unique) -> isikukood char(11)
4. parooli räsimine (midagi peale MD5 ja SHA1)

**Comment by martlaus** [comment]
Iseseisva töö mustripõhises juhendis on kolm triggerit, mida saab maha teha, et saada kätte minimaalne kogus, mida läbimiseks vaja.

**Comment by martlaus** [comment]
töötaja nimest allapoole ja org(esimene) jäid CHECKid tegemata
